services:
  rabbitmq:
    container_name: rabbitmq_agricultural
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'      # AMQP
      - '15672:15672'    # Management UI
    networks:
      - agricultural
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  agricultural:
    driver: bridge

volumes:
  rabbitmq_data: